AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Application

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name (e.g., dev, prod)
  AppName:
    Type: String
    Description: Application name

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.13

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${EnvironmentName}-HelloWorld"
      CodeUri: src/
      Handler: app.lambda_handler
      Environment:
        Variables:
          ENVIRONMENT_NAME: !Ref EnvironmentName
          APP_NAME: !Ref AppName
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  # S3 Bucket example
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-${EnvironmentName}-sample-bucket"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  SampleBucketName:
    Description: "S3 Bucket Name"
    Value: !Ref SampleBucket
