version: 0.2

env:
  parameter-store:
    AUTH0_DOMAIN: /$ENVIRONMENT_NAME/infra-resource/auth0/domain
    AUTH0_CLIENT_ID: /$ENVIRONMENT_NAME/infra-resource/auth0/client-id
    AUTH0_IDENTIFIER: /$ENVIRONMENT_NAME/infra-resource/auth0/identifier

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo PreBuild `date`
      - aws --version
      - sam --version
      - npm ci
      - sed -i "s#__AUTH0_DOMAIN__#$AUTH0_DOMAIN#" .env.production
      - sed -i "s#__AUTH0_CLIENT_ID__#$AUTH0_CLIENT_ID#" .env.production
      - sed -i "s#__AUTH0_IDENTIFIER__#$AUTH0_IDENTIFIER#" .env.production
  build:
    commands:
      - echo Build `date`
      - npm run build -- --base=/$TARGET/
  post_build:
    commands:
      - echo PostBuild `date`
      - aws s3 sync dist/ s3://$S3_BUCKET/$TARGET/ --exclude index.html --delete --quiet
      - aws s3 cp dist/index.html s3://$S3_BUCKET/$TARGET/ --cache-control max-age=$TTL --quiet
