version: 0.2


phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo PreBuild `date`
      - aws --version
      - sam --version
      - npm ci
  build:
    commands:
      - echo Build `date`
      - npm run build -- --base=/$TARGET/
  post_build:
    commands:
      - echo PostBuild `date`
      - aws s3 sync dist/ s3://$S3_BUCKET/$TARGET/ --exclude index.html --delete --quiet
      - aws s3 cp dist/index.html s3://$S3_BUCKET/$TARGET/ --cache-control max-age=$TTL --quiet
