repository:
  # Repository settings
  name: aws-project-template
  description: AWS CloudFormation project template with best practices
  homepage: ""
  topics: ["aws", "cloudformation", "template", "infrastructure"]
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection settings
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        restriction_pushes: true
      restrictions:
        users: []
        teams: []
        apps: []
      allow_force_pushes: false
      allow_deletions: false
      required_linear_history: false

# Label configuration
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  - name: triage
    color: fef2c0
    description: Needs to be reviewed and categorized
  - name: priority-high
    color: d93f0b
    description: High priority issue
  - name: priority-medium
    color: fbca04
    description: Medium priority issue
  - name: priority-low
    color: 0e8a16
    description: Low priority issue