[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
unfixable = ["F401"]

[tool.ruff.lint.isort]
known-first-party = ["app", "common"]

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = ["S101", "SLF001"]

[tool.pytest]
[tool.pytest.ini_options]

[tool.coverage]
[tool.coverage.run]
source = ["app"]
omit = ["app/__main__.py"]
branch = false
