AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 buckets for various AWS services - centralized bucket management'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name (e.g., dev, prd)
    Default: dev
  
  AppName:
    Type: String
    Description: Application name for S3 resources
    Default: infra-s3

Resources:
  # S3 Bucket for Lambda Layer artifacts and packages
  LambdaLayerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-${EnvironmentName}-lambda-layer-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLayerPackages
            Status: Enabled
            Prefix: layers/
            ExpirationInDays: 90
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Purpose
          Value: LambdaLayerStorage

  # S3 Bucket for CodePipeline and CodeBuild artifacts
  CodePipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-${EnvironmentName}-codepipeline-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldPipelineArtifacts
            Status: Enabled
            Prefix: artifacts/
            ExpirationInDays: 30
          - Id: DeleteOldSources
            Status: Enabled
            Prefix: sources/
            ExpirationInDays: 7
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Purpose
          Value: CodePipelineStorage

  # S3 Bucket for CloudFormation templates and deployment artifacts
  CloudFormationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-${EnvironmentName}-cloudformation-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldTemplates
            Status: Enabled
            Prefix: templates/
            ExpirationInDays: 180
          - Id: DeleteOldPackages
            Status: Enabled
            Prefix: packages/
            ExpirationInDays: 90
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Purpose
          Value: CloudFormationStorage

  # S3 Bucket for general application data storage
  ApplicationDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-${EnvironmentName}-appdata-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
              - TransitionInDays: 365
                StorageClass: DEEP_ARCHIVE
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Purpose
          Value: ApplicationDataStorage

Outputs:
  LambdaLayerBucketName:
    Description: Name of the S3 bucket for Lambda Layer packages
    Value: !Ref LambdaLayerBucket
    Export:
      Name: !Sub "${AWS::StackName}-LambdaLayerBucketName"

  LambdaLayerBucketArn:
    Description: ARN of the S3 bucket for Lambda Layer packages
    Value: !GetAtt LambdaLayerBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaLayerBucketArn"

  CodePipelineBucketName:
    Description: Name of the S3 bucket for CodePipeline artifacts
    Value: !Ref CodePipelineBucket
    Export:
      Name: !Sub "${AWS::StackName}-CodePipelineBucketName"

  CodePipelineBucketArn:
    Description: ARN of the S3 bucket for CodePipeline artifacts
    Value: !GetAtt CodePipelineBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CodePipelineBucketArn"

  CloudFormationBucketName:
    Description: Name of the S3 bucket for CloudFormation templates
    Value: !Ref CloudFormationBucket
    Export:
      Name: !Sub "${AWS::StackName}-CloudFormationBucketName"

  CloudFormationBucketArn:
    Description: ARN of the S3 bucket for CloudFormation templates
    Value: !GetAtt CloudFormationBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CloudFormationBucketArn"

  ApplicationDataBucketName:
    Description: Name of the S3 bucket for application data
    Value: !Ref ApplicationDataBucket
    Export:
      Name: !Sub "${AWS::StackName}-ApplicationDataBucketName"

  ApplicationDataBucketArn:
    Description: ARN of the S3 bucket for application data
    Value: !GetAtt ApplicationDataBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ApplicationDataBucketArn"