AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions

Parameters:
  Region:
    Type: String

  EnvironmentPrefix:
    Type: String

  EnvironmentName:
    Type: String

  InfraName:
    Type: String

  CategoryName:
    Type: String

  AppName:
    Type: String

  Target:
    Type: String

  TTL:
    Type: Number

  BucketName:
    Type: String

  DistributionId:
    Type: String

  CodeBuildType:
    Type: String
    Default: ""

  CodeBuildComputeType:
    Type: String
    Default: ""

  CodeBuildImage:
    Type: String
    Default: ""

Mappings:
  Const:
    CodeBuild:
      Type: ARM_CONTAINER
      ComputeType: BUILD_GENERAL1_SMALL
      Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0

Conditions:
  HasCodeBuildType: !Not
    - !Or
      - !Equals
        - !Ref CodeBuildType
        - ""
      - !Equals
        - !Ref CodeBuildType
        - "-"

  HasCodeBuildComputeType: !Not
    - !Or
      - !Equals
        - !Ref CodeBuildComputeType
        - ""
      - !Equals
        - !Ref CodeBuildComputeType
        - "-"

  HasCodeBuildImage: !Not
    - !Or
      - !Equals
        - !Ref CodeBuildImage
        - ""
      - !Equals
        - !Ref CodeBuildImage
        - "-"

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${EnvironmentName}-${AppName}
      PipelineType: V2
      RoleArn:
        Fn::ImportValue: !Sub ${InfraName}-infra-cicd-CodePipelineRole
      ArtifactStore:
        Type: S3
        Location: !Sub wni-${InfraName}-infra-cicd-${Region}
      Stages:
        - Name: Source
          Actions:
            - Name: download-source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                S3Bucket: !Sub wni-${InfraName}-infra-cicd-${Region}
                S3ObjectKey: !Sub artifact/${EnvironmentName}/${AppName}_input.zip
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Approval
          Actions:
            - Name: approve
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
        - Name: Build-Deploy
          Actions:
            - Name: build-deploy
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuild
              InputArtifacts:
                - Name: SourceOutput

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${EnvironmentName}-${AppName}
      ServiceRole:
        Fn::ImportValue: !Sub ${InfraName}-infra-cicd-CodeBuildRole
      Artifacts:
        Type: CODEPIPELINE
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Sub /aws/codebuild/${InfraName}-infra-cicd
          StreamName: !Sub ${EnvironmentName}-${AppName}
      Environment:
        Type: !If
          - HasCodeBuildType
          - !Ref CodeBuildType
          - !FindInMap
            - Const
            - CodeBuild
            - Type
        ComputeType: !If
          - HasCodeBuildComputeType
          - !Ref CodeBuildComputeType
          - !FindInMap
            - Const
            - CodeBuild
            - ComputeType
        Image: !If
          - HasCodeBuildImage
          - !Ref CodeBuildImage
          - !FindInMap
            - Const
            - CodeBuild
            - Image
        EnvironmentVariables:
          - Name: ENVIRONMENT_NAME
            Value: !Ref EnvironmentName
          - Name: APP_NAME
            Value: !Ref AppName
          - Name: TARGET
            Value: !Ref Target
          - Name: TTL
            Value: !Ref TTL
          - Name: S3_BUCKET
            Value: !Ref BucketName
          - Name: DISTRIBUTION_ID
            Value: !Sub "{{resolve:ssm:${DistributionId}}}"
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml

  Events:
    Type: AWS::Events::Rule
    Properties:
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Sub wni-${InfraName}-infra-cicd-${Region}
          object:
            key:
              - !Sub artifact/${EnvironmentName}/${AppName}_input.zip
      Targets:
        - Id: !Sub ${EnvironmentName}-${AppName}
          Arn: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}
          RoleArn:
            Fn::ImportValue: !Sub ${InfraName}-infra-cicd-EventsRole
