AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions

Parameters:
  Region:
    Type: String

  EnvironmentPrefix:
    Type: String

  EnvironmentName:
    Type: String

  InfraName:
    Type: String

  CategoryName:
    Type: String

  AppName:
    Type: String

  Domain:
    Type: String
    Default: ""

Conditions:
  IsEmpty: !Or
    - !Equals
      - !Ref Domain
      - ""
    - !Equals
      - !Ref Domain
      - "-"

Resources:
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2and3
        PriceClass: PriceClass_All
        Logging:
          Bucket: !Sub ${Bucket}.s3.amazonaws.com
          Prefix: cloudfront/
        Aliases:
          - !If
            - IsEmpty
            - !Sub "${EnvironmentName}.{{resolve:ssm:/${InfraName}/infra-resource/host-zone/domain}}"
            - !Ref Domain
        ViewerCertificate:
          AcmCertificateArn: !Sub "{{resolve:ssm:/${InfraName}/infra-resource/acm/arn}}"
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: !Sub ${EnvironmentName}-${AppName}-s3
            DomainName: !Sub ${EnvironmentName}-${CategoryName}-bucket-ane1.s3.ap-northeast-1.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
          - Id: !Sub ${EnvironmentName}-${AppName}-api
            DomainName: !Sub "${EnvironmentName}-api-common.{{resolve:ssm:/${InfraName}/infra-resource/host-zone/domain}}"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Sub ${EnvironmentName}-${AppName}-s3
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: !Ref S3CachePolicy
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
          ResponseHeadersPolicyId: 60669652-455b-4ae9-85a4-c4c02393f86c
          ViewerProtocolPolicy: redirect-to-https
          TrustedKeyGroups:
            - Fn::ImportValue: !Sub ${EnvironmentName}-infra-keypair-KeyGroup
        CacheBehaviors:
          - TargetOriginId: !Sub ${EnvironmentName}-${AppName}-s3
            PathPattern: /public/*
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
            ResponseHeadersPolicyId: 60669652-455b-4ae9-85a4-c4c02393f86c
            ViewerProtocolPolicy: redirect-to-https
          - TargetOriginId: !Sub ${EnvironmentName}-${AppName}-api
            PathPattern: /api/*
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachePolicyId: !Ref ApiCachePolicy
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
            ResponseHeadersPolicyId: 60669652-455b-4ae9-85a4-c4c02393f86c
            ViewerProtocolPolicy: redirect-to-https
          - TargetOriginId: !Sub ${EnvironmentName}-${AppName}-api
            PathPattern: /customer/*
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachePolicyId: !Ref ApiCachePolicy
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
            ResponseHeadersPolicyId: 60669652-455b-4ae9-85a4-c4c02393f86c
            ViewerProtocolPolicy: redirect-to-https

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${EnvironmentName}-${AppName}
        Description: !Sub ${EnvironmentName}-${AppName}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  S3CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub ${EnvironmentName}-${AppName}-s3
        DefaultTTL: 86400
        MinTTL: 0
        MaxTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          CookiesConfig:
            CookieBehavior: whitelist
            Cookies:
              - cloudfront-policy
              - cloudfront-signature
              - cloudfront-key-pair-id
          QueryStringsConfig:
            QueryStringBehavior: none

  ApiCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub ${EnvironmentName}-${AppName}-api
        DefaultTTL: 86400
        MinTTL: 0
        MaxTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - authorization
          CookiesConfig:
            CookieBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  RecordSet:
    Condition: IsEmpty
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "${EnvironmentName}.{{resolve:ssm:/${InfraName}/infra-resource/host-zone/domain}}"
      HostedZoneId: !Sub "{{resolve:ssm:/${InfraName}/infra-resource/host-zone/id}}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-${AppName}-${Region}
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      LifecycleConfiguration:
        Rules:
          - Id: !Sub ${EnvironmentName}-${AppName}-delete-multipart
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: !Sub ${EnvironmentName}-${AppName}-glacier-ir
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER_IR
                TransitionInDays: 90

Outputs:
  CloudFront:
    Value: !Ref CloudFront
    Export:
      Name: !Sub ${EnvironmentName}-${AppName}-CloudFront
