AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions

Parameters:
  Region:
    Type: String

  EnvironmentPrefix:
    Type: String

  EnvironmentName:
    Type: String

  InfraName:
    Type: String

  CategoryName:
    Type: String

  AppName:
    Type: String

Resources:
  CriticalBackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: !Sub ${EnvironmentName}-${AppName}-critical
        BackupPlanRule:
          - RuleName: !Sub ${EnvironmentName}-${AppName}-daily-7days
            TargetBackupVault: Default
            ScheduleExpression: cron(00 17 ? * * *)
            StartWindowMinutes: 120
            Lifecycle:
              DeleteAfterDays: 7
          - RuleName: !Sub ${EnvironmentName}-${AppName}-weekly-1year
            TargetBackupVault: Default
            ScheduleExpression: cron(00 17 ? * 1 *)
            StartWindowMinutes: 120
            Lifecycle:
              MoveToColdStorageAfterDays: 1
              DeleteAfterDays: 400

  CriticalSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref CriticalBackupPlan
      BackupSelection:
        SelectionName: !Sub ${EnvironmentName}-${AppName}-critical
        IamRoleArn: !GetAtt BackupRole.Arn
        ListOfTags:
          - ConditionType: STRINGEQUALS
            ConditionKey: BackupPlan
            ConditionValue: Critical

  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: backup.amazonaws.com
